//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerRequests
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialsType_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaterialsType_()
        {
            this.Materials_ = new HashSet<Materials_>();
        }
    
        public int idMaterialsType { get; set; }
        public string NameMaterialsType { get; set; }
        public decimal PercentageOfLossOfRawMaterials { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materials_> Materials_ { get; set; }
    }
}
