//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerRequests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials_()
        {
            this.ProductMaterials_ = new HashSet<ProductMaterials_>();
        }
    
        public int idMaterials { get; set; }
        public int idMaterialsType { get; set; }
        public string NameMaterials { get; set; }
        public string UnitMeasurement { get; set; }
        public Nullable<decimal> UnitPriceMaterial { get; set; }
        public Nullable<decimal> QuantityInStock { get; set; }
        public Nullable<decimal> MinimumQuantity { get; set; }
        public Nullable<decimal> QuantityPerPackage { get; set; }
    
        public virtual MaterialsType_ MaterialsType_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMaterials_> ProductMaterials_ { get; set; }
    }
}
