//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerRequests
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerRequests_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartnerRequests_()
        {
            this.RequestProducts_ = new HashSet<RequestProducts_>();
        }
    
        public int idRequest { get; set; }
        public int idPartner { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Status { get; set; }
    
        public virtual Partners Partners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestProducts_> RequestProducts_ { get; set; }
    }
}
