//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerRequests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products_()
        {
            this.ProductMaterials_ = new HashSet<ProductMaterials_>();
            this.RequestProducts_ = new HashSet<RequestProducts_>();
        }
    
        public int idProduct { get; set; }
        public int idProductType { get; set; }
        public string ProductName { get; set; }
        public string Article { get; set; }
        public decimal MinPartnerPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMaterials_> ProductMaterials_ { get; set; }
        public virtual ProductType_ ProductType_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestProducts_> RequestProducts_ { get; set; }
    }
}
