//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerRequests
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaterials_
    {
        public int idProductMaterial { get; set; }
        public int idProduct { get; set; }
        public int idMaterials { get; set; }
        public decimal MaterialQuantity { get; set; }
    
        public virtual Materials_ Materials_ { get; set; }
        public virtual Products_ Products_ { get; set; }
    }
}
