//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerRequests
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestProducts_
    {
        public int idRequestProduct { get; set; }
        public int idRequest { get; set; }
        public int idProduct { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
    
        public virtual PartnerRequests_ PartnerRequests_ { get; set; }
        public virtual Products_ Products_ { get; set; }
    }
}
